#!/bin/bash
IMAGE_NAME="minerva-db:5.0"
REGISTRY="docker-registry.hendrikx-itc.nl:5000"
buildtype=${1:-production}
workdir="$(dirname "$0")"
pushd $workdir > /dev/null
echo "changed work dir to '$workdir'"
echo 'building...'
docker build -t $IMAGE_NAME -f $buildtype.dockerfile .
docker tag $IMAGE_NAME "$REGISTRY/$IMAGE_NAME"
docker push "$REGISTRY/$IMAGE_NAME"
echo 'done'
popd
