[workspace]
members = [
    "crates/minerva",
    "crates/cli",
    "crates/admin-service",
    "crates/integration-tests"
]
resolver = "2"

[workspace.package]
version = "6.2.1"
authors = ["Alfred Blokland <alfred.blokland@hendrikx-itc.nl>"]
edition = "2021"
license = "GPL-3.0-or-later"
