version: "3.3"
services:
  db:
    build:
      context: ./
      dockerfile: develop.dockerfile
    container_name: minerva50db
    ports:
      - "16050:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./tests:/tests
      - ./test_results:/test_results
      - ./src:/minerva
    tmpfs:
      - /var/lib/postgresql/data
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
