

CREATE OR REPLACE FUNCTION "system"."version"()
    RETURNS system.version_tuple
AS $$
SELECT (5,1,2)::system.version_tuple;
$$ LANGUAGE sql IMMUTABLE;


DROP FUNCTION "trend_directory"."define_table_trend"(integer, name, text, text, text, text);

DROP FUNCTION "trend_directory"."define_trend_store_part"(integer, name, trend_directory.trend_descr[]);

DROP FUNCTION "trend_directory"."add_trend_to_trend_store"(trend_directory.trend_store_part, trend_directory.table_trend);

DROP FUNCTION "trend_directory"."add_trend_to_trend_store"(trend_directory.trend_store_part, name, text, text, text, text);

DROP FUNCTION "trend_directory"."create_table_trend"(trend_directory.trend_store_part, trend_directory.trend_descr);

DROP FUNCTION "trend_directory"."assure_table_trends_exist"(trend_directory.trend_store_part, trend_directory.trend_descr[]);

DROP FUNCTION "trend_directory"."add_missing_trends"(trend_directory.trend_store, trend_directory.trend_store_part_descr[]);

DROP TABLE "trend_directory"."group_priority";

CREATE TABLE "trend_directory"."generated_table_trend"
(
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "trend_store_part_id" integer NOT NULL,
  "name" name NOT NULL,
  "data_type" text NOT NULL,
  "expression" text NOT NULL,
  "extra_data" jsonb NOT NULL DEFAULT '{}',
  "description" text NOT NULL,
  PRIMARY KEY (id)
);

GRANT SELECT ON TABLE "trend_directory"."generated_table_trend" TO minerva;

GRANT INSERT,UPDATE,DELETE ON TABLE "trend_directory"."generated_table_trend" TO minerva_writer;



CREATE TYPE "trend_directory"."generated_trend_descr" AS (
  "name" name,
  "data_type" text,
  "description" text,
  "expression" text,
  "extra_data" jsonb
);



ALTER TYPE "trend_directory"."trend_descr" ADD ATTRIBUTE "extra_data" jsonb;

ALTER TYPE "trend_directory"."trend_store_part_descr" ADD ATTRIBUTE "generated_trends" trend_directory.generated_trend_descr[];

CREATE FUNCTION "trend_directory"."column_spec"(trend_directory.table_trend)
    RETURNS text
AS $$
SELECT format('%I %s', $1.name, $1.data_type);
$$ LANGUAGE sql IMMUTABLE;


CREATE FUNCTION "trend_directory"."column_spec"(trend_directory.generated_table_trend)
    RETURNS text
AS $$
SELECT format('%I %s GENERATED ALWAYS AS (%s) STORED', $1.name, $1.data_type, $1.expression);
$$ LANGUAGE sql IMMUTABLE;


CREATE FUNCTION "trend_directory"."column_specs"(trend_directory.trend_store_part)
    RETURNS text[]
AS $$
SELECT array_agg(c) FROM (
  SELECT trend_directory.column_spec(t) AS c
  FROM trend_directory.table_trend t
  WHERE t.trend_store_part_id = $1.id
  UNION ALL
  SELECT trend_directory.column_spec(t) AS c
  FROM trend_directory.generated_table_trend t
  WHERE t.trend_store_part_id = $1.id
) combined_columns;
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "trend_directory"."define_table_trend"("trend_store_part_id" integer, trend_directory.trend_descr)
    RETURNS trend_directory.table_trend
AS $$
INSERT INTO trend_directory.table_trend (trend_store_part_id, name, data_type, description, time_aggregation, entity_aggregation)
VALUES ($1, $2.name, $2.data_type, $2.description, $2.time_aggregation, $2.entity_aggregation)
RETURNING table_trend;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."define_generated_table_trend"("trend_store_part_id" integer, trend_directory.generated_trend_descr)
    RETURNS trend_directory.generated_table_trend
AS $$
INSERT INTO trend_directory.generated_table_trend (trend_store_part_id, name, data_type, expression, extra_data, description)
VALUES ($1, $2.name, $2.data_type, $2.expression, $2.extra_data, $2.description)
RETURNING generated_table_trend;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."define_generated_table_trends"(trend_directory.trend_store_part, trend_directory.generated_trend_descr[])
    RETURNS trend_directory.trend_store_part
AS $$
INSERT INTO trend_directory.generated_table_trend(trend_store_part_id, name, data_type, expression, extra_data, description) (
    SELECT $1.id, name, data_type, expression, extra_data, description
    FROM unnest($2)
);

SELECT $1;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."define_trend_store_part"("trend_store_id" integer, "name" name, "trends" trend_directory.trend_descr[], "generated_trends" trend_directory.generated_trend_descr[])
    RETURNS trend_directory.trend_store_part
AS $$
SELECT 
trend_directory.define_generated_table_trends(
  trend_directory.define_table_trends(
      trend_directory.define_trend_store_part($1, $2),
      $3
  ),
  $4
);
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."get_trend_store_parts"("trend_store_id" integer)
    RETURNS trend_directory.trend_store_part
AS $$
SELECT trend_store_part FROM trend_directory.trend_store_part WHERE trend_store_id = $1
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."add_column_sql_part"(trend_directory.table_trend)
    RETURNS text
AS $$
SELECT format('ADD COLUMN %I %s', $1.name, $1.data_type);
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "trend_directory"."add_trends_to_trend_store_part"(trend_directory.trend_store_part, trend_directory.table_trend[])
    RETURNS trend_directory.trend_store_part
AS $$
SELECT public.action(
  $1,
  ARRAY[
    format(
      'ALTER TABLE %I.%I %s;',
      trend_directory.base_table_schema(),
      trend_directory.base_table_name($1),
      (SELECT string_agg(trend_directory.add_column_sql_part(t), ',') FROM unnest($2) AS t)
    ),
    format(
      'ALTER TABLE %I.%I %s;',
      trend_directory.staging_table_schema(),
      trend_directory.staging_table_name($1),
      (SELECT string_agg(trend_directory.add_column_sql_part(t), ',') FROM unnest($2) AS t)
    )
  ]
);
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."add_generated_column_sql_part"(trend_directory.generated_table_trend)
    RETURNS text
AS $$
SELECT format(
  'ADD COLUMN %I %s GENERATED ALWAYS AS (%s) STORED',
  $1.name, $1.data_type, $1.expression
);
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "trend_directory"."add_generated_trends_to_trend_store_part"(trend_directory.trend_store_part, trend_directory.generated_table_trend[])
    RETURNS trend_directory.trend_store_part
AS $$
SELECT public.action(
  $1,
  ARRAY[
    format(
      'ALTER TABLE %I.%I %s;',
      trend_directory.base_table_schema(),
      trend_directory.base_table_name($1),
      (SELECT string_agg(trend_directory.add_generated_column_sql_part(t), ',') FROM unnest($2) AS t)
    ),
    format(
      'ALTER TABLE %I.%I %s;',
      trend_directory.staging_table_schema(),
      trend_directory.staging_table_name($1),
      (SELECT string_agg(trend_directory.add_generated_column_sql_part(t), ',') FROM unnest($2) AS t)
    )
  ]
);
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."create_generated_table_trends"(trend_directory.trend_store_part, trend_directory.generated_trend_descr[])
    RETURNS trend_directory.trend_store_part
AS $$
SELECT trend_directory.add_generated_trends_to_trend_store_part(
  $1,
  array_agg(trend_directory.define_generated_table_trend($1.id, t))
) FROM unnest($2) AS t
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."missing_generated_table_trends"(trend_directory.trend_store_part, "required" trend_directory.generated_trend_descr[])
    RETURNS SETOF trend_directory.generated_trend_descr
AS $$
SELECT required
FROM unnest($2) required
LEFT JOIN trend_directory.generated_table_trend
ON generated_table_trend.name = required.name AND generated_table_trend.trend_store_part_id = $1.id
WHERE generated_table_trend.id IS NULL;
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "trend_directory"."assure_table_trends_exist"(trend_directory.trend_store_part, trend_directory.trend_descr[], trend_directory.generated_trend_descr[])
    RETURNS trend_directory.trend_store_part
AS $$
DECLARE
  missing_trends trend_directory.trend_descr[];
  missing_generated_trends trend_directory.generated_trend_descr[];
BEGIN
  -- Normal trends
  SELECT array_agg(t) INTO missing_trends
  FROM trend_directory.missing_table_trends($1, $2) AS t;

  IF array_length(missing_trends, 1) > 0 THEN
    PERFORM trend_directory.create_table_trends($1, missing_trends);
  END IF;

  -- Generated trends
  SELECT array_agg(t) INTO missing_generated_trends
  FROM trend_directory.missing_generated_table_trends($1, $3) AS t;

  IF array_length(missing_generated_trends, 1) > 0 THEN
    PERFORM trend_directory.create_generated_table_trends($1, missing_generated_trends);
  END IF;

  RETURN $1;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE FUNCTION "trend_directory"."add_trends"(trend_directory.trend_store, "parts" trend_directory.trend_store_part_descr[])
    RETURNS trend_directory.trend_store
AS $$
SELECT trend_directory.assure_table_trends_exist(
  trend_directory.get_or_create_trend_store_part($1.id, name),
  trends,
  generated_trends
)
FROM unnest($2);

SELECT $1;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."remove_table_trend"("trend" trend_directory.table_trend)
    RETURNS trend_directory.table_trend
AS $$
BEGIN
  EXECUTE FORMAT('ALTER TABLE trend.%I DROP COLUMN %I',
    trend_directory.trend_store_part_name_for_trend(trend), trend.name);
  EXECUTE FORMAT('ALTER TABLE trend.%I_staging DROP COLUMN %I',
    trend_directory.trend_store_part_name_for_trend(trend), trend.name);
  DELETE FROM trend_directory.table_trend WHERE id = trend.id;
  RETURN t FROM trend_directory.table_trend t WHERE 0=1;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE FUNCTION "trend_directory"."trend_store_part_name_for_trend"("trend" trend_directory.table_trend)
    RETURNS name
AS $$
SELECT trend_store_part.name FROM trend_directory.table_trend LEFT JOIN trend_directory.trend_store_part
  ON table_trend.trend_store_part_id = trend_store_part.id
  WHERE table_trend.id = trend.id;
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "trend_directory"."get_trends_for_trend_store"("trend_store_id" integer)
    RETURNS SETOF trend_directory.table_trend
AS $$
SELECT table_trend
  FROM trend_directory.table_trend
  LEFT JOIN trend_directory.trend_store_part
  ON table_trend.trend_store_part_id = trend_store_part.id
  WHERE trend_store_part.trend_store_id = trend_store_id;
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "trend_directory"."get_trends_for_trend_store"(trend_directory.trend_store)
    RETURNS SETOF trend_directory.table_trend
AS $$
SELECT trend_directory.get_trends_for_trend_store($1.id);
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "trend_directory"."get_trend_if_defined"("trend" trend_directory.table_trend, "trends" trend_directory.trend_descr[], "partname" text)
    RETURNS trend_directory.table_trend
AS $$
SELECT t FROM trend_directory.table_trend t JOIN unnest($2) t2
  ON t.name = t2.name
  WHERE t.id = $1.id
  AND trend_directory.trend_store_part_name_for_trend(t) = $3;
$$ LANGUAGE sql VOLATILE;

COMMENT ON FUNCTION "trend_directory"."get_trend_if_defined"("trend" trend_directory.table_trend, "trends" trend_directory.trend_descr[], "partname" text) IS 'Return the trend, but only if it is a trend defined by trends';


CREATE FUNCTION "trend_directory"."remove_trend_if_extraneous"("trend" trend_directory.table_trend, "parts" trend_directory.trend_store_part_descr[])
    RETURNS void
AS $$
SELECT COALESCE(
  trend_directory.get_trend_if_defined($1, trends, name),
  trend_directory.remove_table_trend($1)
)
FROM unnest($2);
$$ LANGUAGE sql VOLATILE;

COMMENT ON FUNCTION "trend_directory"."remove_trend_if_extraneous"("trend" trend_directory.table_trend, "parts" trend_directory.trend_store_part_descr[]) IS 'Remove the trend if it is not one that is described by parts';


CREATE FUNCTION "trend_directory"."remove_extra_trends"(trend_directory.trend_store, "parts" trend_directory.trend_store_part_descr[])
    RETURNS trend_directory.trend_store
AS $$
SELECT trend_directory.remove_trend_if_extraneous(
  trend_directory.get_trends_for_trend_store($1), $2);
SELECT $1;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."change_table_trend_data_unsafe"(trend_directory.table_trend, "data_type" text, "entity_aggregation" text, "time_aggregation" text)
    RETURNS trend_directory.table_trend
AS $$
BEGIN
  UPDATE trend_directory.table_trend SET
    data_type = $2,
    entity_aggregation = $3,
    time_aggregation = $4
  WHERE id = $1.id;
  EXECUTE format('ALTER TABLE trend.%I ALTER %I TYPE %s USING CAST(%I AS %s)',
    trend_directory.trend_store_part_name_for_trend($1),
    $1.name,
    $2,
    $1.name,
    $2);
  RETURN $1;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE FUNCTION "trend_directory"."change_table_trend_data_safe"(trend_directory.table_trend, "data_type" text, "entity_aggregation" text, "time_aggregation" text)
    RETURNS trend_directory.table_trend
AS $$
SELECT trend_directory.change_table_trend_data_unsafe(
  $1,
  trend_directory.greatest_data_type($2, $1.data_type),
  $3,
  $4);
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."change_trend_data_unsafe"("trend" trend_directory.table_trend, "trends" trend_directory.trend_descr[], "partname" text)
    RETURNS void
AS $$
SELECT trend_directory.change_table_trend_data_unsafe($1, t.data_type, t.entity_aggregation, t.time_aggregation)
  FROM unnest($2) t
  WHERE t.name = $1.name AND trend_directory.trend_store_part_name_for_trend($1) = $3;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."change_trend_data_safe"("trend" trend_directory.table_trend, "trends" trend_directory.trend_descr[], "partname" text)
    RETURNS void
AS $$
SELECT trend_directory.change_table_trend_data_safe($1, t.data_type, t.entity_aggregation, t.time_aggregation)
  FROM unnest($2) t
  WHERE t.name = $1.name AND trend_directory.trend_store_part_name_for_trend($1) = $3;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."change_all_trend_data"(trend_directory.trend_store, "parts" trend_directory.trend_store_part_descr[])
    RETURNS trend_directory.trend_store
AS $$
SELECT trend_directory.change_trend_data_unsafe(
  trend_directory.get_trends_for_trend_store($1), trends, name)
  FROM unnest($2);
SELECT $1;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."change_trend_data_upward"(trend_directory.trend_store, "parts" trend_directory.trend_store_part_descr[])
    RETURNS trend_directory.trend_store
AS $$
SELECT trend_directory.change_trend_data_safe(
  trend_directory.get_trends_for_trend_store($1), trends, name)
  FROM unnest($2);
SELECT $1;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."change_trendstore_strong"(trend_directory.trend_store, "parts" trend_directory.trend_store_part_descr[])
    RETURNS trend_directory.trend_store
AS $$
SELECT trend_directory.change_all_trend_data(
  trend_directory.remove_extra_trends(
  trend_directory.add_trends(
  $1, $2
), $2
), $2);
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "trend_directory"."change_trendstore_weak"(trend_directory.trend_store, "parts" trend_directory.trend_store_part_descr[])
    RETURNS trend_directory.trend_store
AS $$
SELECT trend_directory.change_trend_data_upward(
  trend_directory.remove_extra_trends(
  trend_directory.add_trends(
  $1, $2
), $2
), $2);
$$ LANGUAGE sql VOLATILE;


CREATE OR REPLACE FUNCTION "trend_directory"."create_base_table_sql"(trend_directory.trend_store_part)
    RETURNS text[]
AS $$
SELECT ARRAY[
    format(
        'CREATE TABLE %I.%I ('
        'entity_id integer NOT NULL, '
        '"timestamp" timestamp with time zone NOT NULL, '
        'created timestamp with time zone NOT NULL, '
        'job_id bigint NOT NULL, '
        '%s'
        ') PARTITION BY RANGE ("timestamp");',
        trend_directory.base_table_schema(),
        trend_directory.base_table_name($1),
        array_to_string(trend_directory.column_specs($1), ',')
    ),
    format(
        'ALTER TABLE %I.%I ADD PRIMARY KEY (entity_id, "timestamp");',
        trend_directory.base_table_schema(),
        trend_directory.base_table_name($1)
    ),
    format(
        'CREATE INDEX ON %I.%I USING btree (job_id)',
        trend_directory.base_table_schema(),
        trend_directory.base_table_name($1)
    ),
    format(
        'CREATE INDEX ON %I.%I USING btree (timestamp);',
        trend_directory.base_table_schema(),
        trend_directory.base_table_name($1)
    ),
    format(
        'GRANT SELECT ON TABLE %I.%I TO minerva;',
        trend_directory.base_table_schema(),
        trend_directory.base_table_name($1)
    ),
    format(
        'GRANT INSERT,DELETE,UPDATE ON TABLE %I.%I TO minerva_writer;',
        trend_directory.base_table_schema(),
        trend_directory.base_table_name($1)
    )
];
$$ LANGUAGE sql STABLE STRICT;


CREATE OR REPLACE FUNCTION "trend_directory"."create_staging_table_sql"(trend_directory.trend_store_part)
    RETURNS text[]
AS $$
SELECT ARRAY[
    format(
        'CREATE UNLOGGED TABLE %I.%I (entity_id integer, "timestamp" timestamp with time zone%s);',
        trend_directory.staging_table_schema(),
        trend_directory.staging_table_name($1),
        (
            SELECT string_agg(format(', %I %s', t.name, t.data_type), ' ')
            FROM trend_directory.table_trend t
            WHERE t.trend_store_part_id = $1.id
        )
    ),
    format(
        'ALTER TABLE ONLY %I.%I ADD PRIMARY KEY (entity_id, "timestamp");',
        trend_directory.staging_table_schema(),
        trend_directory.staging_table_name($1)
    ),
    format(
        'GRANT SELECT ON TABLE %I.%I TO minerva;',
        trend_directory.staging_table_schema(),
        trend_directory.staging_table_name($1)
    ),
    format(
        'GRANT INSERT,DELETE,UPDATE ON TABLE %I.%I TO minerva_writer;',
        trend_directory.staging_table_schema(),
        trend_directory.staging_table_name($1)
    )
];
$$ LANGUAGE sql STABLE;


CREATE OR REPLACE FUNCTION "trend_directory"."get_view_trends"("view_name" name)
    RETURNS SETOF trend_directory.trend_descr
AS $$
SELECT (a.attname, format_type(a.atttypid, a.atttypmod), 'deduced from view', 'sum', 'sum', '{}')::trend_directory.trend_descr
FROM pg_class c
JOIN pg_attribute a ON a.attrelid = c.oid
WHERE c.relname = $1 AND a.attnum >= 0 AND NOT a.attisdropped;
$$ LANGUAGE sql STABLE;


CREATE OR REPLACE FUNCTION "trend_directory"."show_trends"(trend_directory.trend_store_part)
    RETURNS SETOF trend_directory.trend_descr
AS $$
SELECT
    table_trend.name::name,
    format_type(a.atttypid, a.atttypmod)::text,
    table_trend.description,
    table_trend.time_aggregation,
    table_trend.entity_aggregation,
    table_trend.extra_data
FROM trend_directory.table_trend
JOIN pg_catalog.pg_class c ON c.relname = $1::text
JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
JOIN pg_catalog.pg_attribute a ON a.attrelid = c.oid AND a.attname = table_trend.name
WHERE
    n.nspname = 'trend' AND
    a.attisdropped = false AND
    a.attnum > 0 AND table_trend.trend_store_part_id = $1.id;
$$ LANGUAGE sql STABLE;


CREATE OR REPLACE FUNCTION "trend_directory"."define_table_trends"(trend_directory.trend_store_part, trend_directory.trend_descr[])
    RETURNS trend_directory.trend_store_part
AS $$
INSERT INTO trend_directory.table_trend(name, data_type, trend_store_part_id, description, time_aggregation, entity_aggregation, extra_data) (
    SELECT name, data_type, $1.id, description, time_aggregation, entity_aggregation, extra_data
    FROM unnest($2)
);

SELECT $1;
$$ LANGUAGE sql VOLATILE;


CREATE OR REPLACE FUNCTION "trend_directory"."define_trend_store"(trend_directory.trend_store, trend_directory.trend_store_part_descr[])
    RETURNS trend_directory.trend_store
AS $$
SELECT trend_directory.define_trend_store_part($1.id, name, trends, generated_trends)
FROM unnest($2);

SELECT $1;
$$ LANGUAGE sql VOLATILE;


CREATE OR REPLACE FUNCTION "trend_directory"."create_table_trends"(trend_directory.trend_store_part, trend_directory.trend_descr[])
    RETURNS trend_directory.trend_store_part
AS $$
SELECT trend_directory.add_trends_to_trend_store_part(
  $1,
  array_agg(trend_directory.define_table_trend($1.id, t))
) FROM unnest($2) AS t
$$ LANGUAGE sql VOLATILE;
