

CREATE FUNCTION "public"."action_count"("sql" text)
    RETURNS integer
AS $$
DECLARE
    row_count integer;
BEGIN
    EXECUTE sql;

    GET DIAGNOSTICS row_count = ROW_COUNT;

    RETURN row_count;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE OR REPLACE FUNCTION "system"."version"()
    RETURNS system.version_tuple
AS $$
SELECT (5,1,5)::system.version_tuple;
$$ LANGUAGE sql IMMUTABLE;


CREATE FUNCTION "trend_directory"."missing_generated_table_trends"("trend_store_part" name, "required" trend_directory.generated_trend_descr[])
    RETURNS SETOF trend_directory.generated_trend_descr
AS $$
SELECT trend_directory.missing_generated_table_trends(trend_store_part, $2)
FROM trend_directory.trend_store_part WHERE name = $1
$$ LANGUAGE sql STABLE;


DROP FUNCTION "attribute_directory"."transfer_staged"(attribute_directory.attribute_store);

CREATE TABLE "attribute_directory"."sampled_view_materialization"
(
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "attribute_store_id" integer NOT NULL,
  "src_view" text NOT NULL
);



CREATE FUNCTION "attribute_directory"."transfer_staged"(attribute_directory.attribute_store)
    RETURNS integer
AS $$
DECLARE
    table_name name;
    columns_part text;
    set_columns_part text;
    default_columns text[];
    row_count integer;
BEGIN
    table_name = attribute_directory.to_table_name($1);

    default_columns = ARRAY[
        'entity_id',
        '"timestamp"'
    ];

    SELECT array_to_string(default_columns || array_agg(format('%I', name)), ', ') INTO columns_part
    FROM attribute_directory.attribute
    WHERE attribute_store_id = $1.id;

    EXECUTE format(
        'INSERT INTO attribute_history.%I(%s) SELECT %s FROM attribute_staging.%I',
        table_name, columns_part, columns_part, table_name || '_new'
    );

    GET DIAGNOSTICS row_count = ROW_COUNT;

    SELECT array_to_string(array_agg(format('%I = m.%I', name, name)), ', ') INTO set_columns_part
    FROM attribute_directory.attribute
    WHERE attribute_store_id = $1.id;

    EXECUTE format(
        'UPDATE attribute_history.%I a '
        'SET modified = now(), %s '
        'FROM attribute_staging.%I m '
        'WHERE m.entity_id = a.entity_id AND m.timestamp = a.timestamp',
        table_name, set_columns_part, table_name || '_modified'
    );

    EXECUTE format('TRUNCATE attribute_staging.%I', table_name);

    RETURN row_count;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE FUNCTION "attribute_directory"."view_to_attribute_staging_sql"("view" text, attribute_directory.attribute_store)
    RETURNS text
AS $$
SELECT format(
    'INSERT INTO attribute_staging.%1$I(%2$s) SELECT %2$s FROM %3$s',
    attribute_directory.to_table_name($2),
    array_to_string(ARRAY['entity_id', 'timestamp']::text[] || array_agg(quote_ident(attribute.name)), ', '),
    $1::regclass::text
)
FROM attribute_directory.attribute
WHERE attribute_store_id = $2.id;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "attribute_directory"."stage_sample"(attribute_directory.sampled_view_materialization)
    RETURNS integer
AS $$
SELECT public.action_count(
    attribute_directory.view_to_attribute_staging_sql($1.src_view, attribute_store)
)
FROM attribute_directory.attribute_store
WHERE id = $1.attribute_store_id
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "attribute_directory"."materialize"(attribute_directory.sampled_view_materialization)
    RETURNS integer
AS $$
SELECT attribute_directory.stage_sample($1);

SELECT attribute_directory.transfer_staged(attribute_store)
FROM attribute_directory.attribute_store
WHERE id = $1.attribute_store_id;
$$ LANGUAGE sql VOLATILE;
