

CREATE OR REPLACE FUNCTION "system"."version"()
    RETURNS system.version_tuple
AS $$
SELECT (5,3,3)::system.version_tuple;
$$ LANGUAGE sql IMMUTABLE;


CREATE TABLE "trend_directory"."view_trend"
(
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "trend_view_part_id" integer NOT NULL,
  "name" name NOT NULL,
  "data_type" text NOT NULL,
  "extra_data" jsonb NOT NULL DEFAULT '{}',
  "description" text NOT NULL,
  "time_aggregation" text NOT NULL,
  "entity_aggregation" text NOT NULL,
  PRIMARY KEY (id)
);

GRANT SELECT ON TABLE "trend_directory"."view_trend" TO minerva;

GRANT INSERT,UPDATE,DELETE ON TABLE "trend_directory"."view_trend" TO minerva_writer;



ALTER TABLE "trend_directory"."trend_view_part" DROP COLUMN "trend_store_id";
ALTER TABLE "trend_directory"."trend_view_part" ADD COLUMN "trend_view_id" integer NOT NULL;
