CREATE SCHEMA IF NOT EXISTS "entity_set";
GRANT USAGE ON SCHEMA "entity_set" TO "minerva";

CREATE TABLE "directory"."entity_set"
(
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text,
  "group" text,
  "entity_type_id" integer,
  "owner" text,
  "created" timestamptz DEFAULT now(),
  "modified" timestamptz DEFAULT now(),
  "description" text,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "entity_set_name_idx" ON "directory"."entity_set" USING btree(name, owner);

CREATE INDEX "entity_set_entity_type_idx" ON "directory"."entity_set" USING btree(entity_type_id);

GRANT SELECT ON TABLE "directory"."entity_set" TO minerva;

GRANT INSERT,UPDATE,DELETE ON TABLE "directory"."entity_set" TO minerva_writer;


CREATE FUNCTION "directory"."update_modified_column"()
    RETURNS trigger
AS $$
BEGIN
  NEW.modified = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE TRIGGER update_modified_column
  BEFORE UPDATE ON "directory"."entity_set"
  FOR EACH ROW
  EXECUTE PROCEDURE "directory"."update_modified_column"();


CREATE FUNCTION "entity_set"."get_entity_type_name"(directory.entity_set)
    RETURNS text
AS $$
SELECT name from directory.entity_type WHERE id = $1.entity_type_id;
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "entity_set"."entity_set_exists"("owner" text, "name" text)
    RETURNS boolean
AS $$
SELECT CASE COUNT(*)
  WHEN 0 THEN false
  ELSE true
END
FROM directory.entity_set WHERE owner = $1 AND name = $2;
$$ LANGUAGE sql STABLE;


CREATE FUNCTION "entity_set"."create_entity_set_table_if_not_exist"(directory.entity_type)
    RETURNS void
AS $$
DECLARE
  entity_set_count integer;
BEGIN
  SELECT count(*) FROM directory.entity_set WHERE entity_type_id = $1.id INTO entity_set_count;
  IF entity_set_count = 0
  THEN
    EXECUTE FORMAT(
      'CREATE TABLE IF NOT EXISTS entity_set.%I('
        'id integer,'
        'entity_set_id integer,'
        'primary key (id, entity_set_id)'
      ');',
      $1.name
    );
    EXECUTE FORMAT(
      'GRANT SELECT ON entity_set.%I TO minerva;',
      $1.name
    );
    EXECUTE FORMAT(
      'GRANT INSERT,UPDATE,DELETE ON entity_set.%I to minerva_writer;',
      $1.name
    );
    EXECUTE FORMAT(
      'CREATE INDEX IF NOT EXISTS entity_set_%s_id_idx ON entity_set.%I(id);',
      $1.name,
      $1.name
    );
    EXECUTE FORMAT(
      'CREATE INDEX IF NOT EXISTS entity_set_%s_entityt_set_id_idx ON entity_set.%I(entity_set_id);',
      $1.name,
      $1.name
    );           
  END IF;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE FUNCTION "entity_set"."create_entity_set"("name" text, "group" text, "entity_type_name" text, "owner" text, "description" text)
    RETURNS directory.entity_set
AS $$
DECLARE
  entity_type directory.entity_type;
BEGIN
  SELECT * FROM directory.entity_type et WHERE et.name = entity_type_name INTO entity_type;
  PERFORM entity_set.create_entity_set_table_if_not_exist(et) from directory.entity_type et WHERE et.name = entity_type_name;
  INSERT INTO directory.entity_set(name, "group", entity_type_id, owner, description)
    VALUES ($1, $2, entity_type.id, $4, $5);
  RETURN es FROM directory.entity_set es WHERE es.name = $1 AND es.owner = $4;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE FUNCTION "entity_set"."add_entity_to_set"(directory.entity_set, "entity" text)
    RETURNS void
AS $$
SELECT action(FORMAT(
  'INSERT INTO entity_set.%I(id, entity_set_id) '
   'SELECT id, %s '
   'FROM entity.%I WHERE name = ''%s'' '
   'ON CONFLICT DO NOTHING;',
  entity_set.get_entity_type_name($1),
  $1.id,
  entity_set.get_entity_type_name($1),
  $2
));
UPDATE directory.entity_set SET modified = now() WHERE id = $1.id;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "entity_set"."remove_entity_from_set"(directory.entity_set, "entity" text)
    RETURNS void
AS $$
SELECT action(FORMAT(
  'DELETE FROM entity_set.%I es USING entity.%I e '
  'WHERE es.entity_set_id = %s AND es.id = e.id AND e.name = ''%s'';',
  entity_set.get_entity_type_name($1),
  entity_set.get_entity_type_name($1),
  $1.id,
  $2
));
UPDATE directory.entity_set SET modified = now() WHERE id = $1.id;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "entity_set"."add_entities_to_set"(directory.entity_set, "entities" text[])
    RETURNS void
AS $$
SELECT entity_set.add_entity_to_set($1, e) FROM unnest($2) e;
$$ LANGUAGE sql VOLATILE;


CREATE FUNCTION "entity_set"."change_set_entities"(directory.entity_set, "entities" text[])
    RETURNS void
AS $$
SELECT action(FORMAT(
  'DELETE FROM entity_set.%I WHERE entity_set_id = %s;',
  entity_set.get_entity_type_name($1),
  $1.id
));
UPDATE directory.entity_set SET modified = now() WHERE id = $1.id;
SELECT entity_set.add_entities_to_set($1, $2);
$$ LANGUAGE sql VOLATILE;

COMMENT ON FUNCTION "entity_set"."change_set_entities"(directory.entity_set, "entities" text[]) IS 'Set the entities in the set to exactly the specified entities';


CREATE FUNCTION "entity_set"."change_set_entities_guarded"(directory.entity_set, "entities" text[])
    RETURNS text[]
AS $$
DECLARE
  entity text;
  real_entity text;
  result text[];
  newresult text[];
BEGIN
  SELECT $2 INTO result;
  FOREACH entity IN ARRAY $2 LOOP
    EXECUTE FORMAT(
      'SELECT name FROM entity.%I WHERE name = ''%s'';',
      entity_set.get_entity_type_name($1),
      entity
    ) INTO real_entity;
    SELECT array_remove(result, real_entity) INTO result;
  END LOOP;
  IF ARRAY_LENGTH(result, 1) IS NULL THEN
    PERFORM entity_set.change_set_entities($1, $2);
  END IF;
  RETURN result;
END;
$$ LANGUAGE plpgsql VOLATILE;

COMMENT ON FUNCTION "entity_set"."change_set_entities_guarded"(directory.entity_set, "entities" text[]) IS 'Only sets the entities if all specified entities are actually valid.
Returns those entities that were invalid.';


CREATE FUNCTION "entity_set"."create_entity_set_guarded"("name" text, "group" text, "entity_type_name" text, "owner" text, "description" text, "entities" text[])
    RETURNS text[]
AS $$
DECLARE
  entity text;
  real_entity text;
  result text[];
  newresult text[];
  entityset integer;
BEGIN
  SELECT $6 INTO result;
  FOREACH entity IN ARRAY $6 LOOP
    EXECUTE FORMAT(
      'SELECT name FROM entity.%I WHERE name = ''%s'';',
      $3,
      entity
    ) INTO real_entity;
    SELECT array_remove(result, real_entity) INTO result;
  END LOOP;
  IF ARRAY_LENGTH(result, 1) IS NULL THEN
    SELECT id FROM entity_set.create_entity_set($1, $2, $3, $4, $5) INTO entityset;
    PERFORM entity_set.change_set_entities(t, $6) 
      FROM directory.entity_set t
      WHERE t.id = entityset;
  END IF;
  RETURN result;
END;
$$ LANGUAGE plpgsql VOLATILE;


CREATE FUNCTION "entity_set"."get_entity_set_members"(directory.entity_set)
    RETURNS text[]
AS $$
DECLARE
  result text[];
BEGIN
  EXECUTE FORMAT(
    'SELECT array_agg(e.name) '
    'FROM entity_set.%I es JOIN entity.%I e ON es.id = e.id '
    'WHERE es.entity_set_id = %s',
    entity_set.get_entity_type_name($1),
    entity_set.get_entity_type_name($1),
    $1.id
  ) INTO result;
  RETURN result;
END;
$$ LANGUAGE plpgsql STABLE;


CREATE FUNCTION "entity_set"."get_entity_set_members"("owner" text, "name" text)
    RETURNS text[]
AS $$
SELECT entity_set.get_entity_set_members(es) FROM directory.entity_set es WHERE owner = $1 AND name = $2;
$$ LANGUAGE sql STABLE;


ALTER TABLE "directory"."entity_set"
  ADD CONSTRAINT "entity_set_entity_type_id_fkey"
  FOREIGN KEY (entity_type_id)
  REFERENCES "directory"."entity_type" (id) ON DELETE CASCADE;
